/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfessionRouteImport } from './routes/confession'
import { Route as IndexRouteImport } from './routes/index'

const ConfessionRoute = ConfessionRouteImport.update({
  id: '/confession',
  path: '/confession',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confession': typeof ConfessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confession': typeof ConfessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confession': typeof ConfessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/confession'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/confession'
  id: '__root__' | '/' | '/confession'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfessionRoute: typeof ConfessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confession': {
      id: '/confession'
      path: '/confession'
      fullPath: '/confession'
      preLoaderRoute: typeof ConfessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfessionRoute: ConfessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
