/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfessionRouteImport } from './routes/confession'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfessionTokenRouteImport } from './routes/confession.$token'

const ConfessionRoute = ConfessionRouteImport.update({
  id: '/confession',
  path: '/confession',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessionTokenRoute = ConfessionTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ConfessionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confession': typeof ConfessionRouteWithChildren
  '/confession/$token': typeof ConfessionTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confession': typeof ConfessionRouteWithChildren
  '/confession/$token': typeof ConfessionTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confession': typeof ConfessionRouteWithChildren
  '/confession/$token': typeof ConfessionTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/confession' | '/confession/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/confession' | '/confession/$token'
  id: '__root__' | '/' | '/confession' | '/confession/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfessionRoute: typeof ConfessionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confession': {
      id: '/confession'
      path: '/confession'
      fullPath: '/confession'
      preLoaderRoute: typeof ConfessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confession/$token': {
      id: '/confession/$token'
      path: '/$token'
      fullPath: '/confession/$token'
      preLoaderRoute: typeof ConfessionTokenRouteImport
      parentRoute: typeof ConfessionRoute
    }
  }
}

interface ConfessionRouteChildren {
  ConfessionTokenRoute: typeof ConfessionTokenRoute
}

const ConfessionRouteChildren: ConfessionRouteChildren = {
  ConfessionTokenRoute: ConfessionTokenRoute,
}

const ConfessionRouteWithChildren = ConfessionRoute._addFileChildren(
  ConfessionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfessionRoute: ConfessionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
